import os

Import('env')

localEnv = env.Clone()

source = [
    'Buffer.cpp',
    'CircularBuffer.cpp',
    'Crc16.cpp',
    'Hdlc.cpp',
    'Mutex.cpp',
    'Queue.cpp',
    'Scheduler.cpp',
    'Semaphore.cpp',
    'Serial.cpp',
    'Task.cpp'
]

common  = localEnv.Object(source=source)

Return('common')
