# Project name and files to compile
PROJECT_NAME  = digiproces
PROJECT_FILES = main.cpp

# Location of the root directory
PROJECT_HOME = ../..

# Configure compiling
USE_KERNEL = FALSE

# Append to the include path
INC_PATH += -I .

# Include the Makefile in the root directory
include $(PROJECT_HOME)/Makefile.include    
