import os

Import('env')

localEnv = env.Clone()

target = 'libsys'

src_dir   = ['src']
output_dir = os.path.join('#', 'bin', env['board'])
source = []

for src in src_dir:
    script = os.path.join('#', 'sys', src, 'SConscript')
    build  = os.path.join('#', 'build', localEnv['board'], 'sys', src)
    output = localEnv.SConscript(
        script,
        variant_dir = build,
        duplicate = 0,
        exports = {'env': env},
    )
    source.append(output)

libstack = localEnv.StaticLibrary(
    target = target,
    source = source,
)

result = env.Install(output_dir, libstack)
