import os

Import('env')

localEnv = env.Clone()

target = 'ieee802154-sniffer.elf'
source = ['main.cpp']

output = localEnv.Program(
    target = target,
    source = source,
    LIBS = env['lib_name'],
    LIBPATH = env['lib_path']
)

Return('output')
