import os

Import('env')

localEnv = env.Clone()

################################################################################

source = [
	'Aes.cpp',
    'Board.cpp',
    'cc2538_startup.c',
    'Gpio.cpp',
    'GpioAdc.cpp',
    'GpioIn.cpp',
    'GpioInPow.cpp',
    'GpioOut.cpp',
    'GpioPwm.cpp',
    'I2c.cpp',
    'InterruptHandler.cpp',
    'Radio.cpp',
    'RadioTimer.cpp',
    'RandomNumberGenerator.cpp',
    'SleepTimer.cpp',
    'Spi.cpp',
    'SysTick.cpp',
    'TemperatureSensor.cpp',
    'Timer.cpp',
    'Uart.cpp',
    'Watchdog.cpp',
]

common = localEnv.Object(source=source)

Return('common')

################################################################################
