import os

Import('env')

localEnv = env.Clone()

localEnv.Append(CFLAGS = '-DNO_CLOCK_DIVIDER_RESTORE')

source = [
    'adc.c',
    'aes.c',
    'ccm.c',
    'cpu.c',
    'debug.c',
    'flash.c',
    'gpio.c',
    'gptimer.c',
    'i2c.c',
    'interrupt.c',
    'ioc.c',
    'pka.c',
    'sha256.c',
    'sleepmode.c',
    'ssi.c',
    'sys_ctrl.c',
    'systick.c',
    'uart.c',
    'udma.c',
    'watchdog.c'
]

common = localEnv.Object(source=source)

Return('common')
