import os

Import('env')

localEnv = env.Clone()

project   = 'freertos-cc2538'
extension = '.elf'

target = project + extension
source = [
    'main.cpp'
]

main = localEnv.Program(
    target = target,
    source = source,
    LIBS = env['lib_name'],
    LIBPATH = env['lib_path']
)

Return('main')
