# Append to the files to compile
SRC_FILES += Buffer.cpp CircularBuffer.cpp Crc16.cpp Hdlc.cpp LinkedList.cpp Logging.cpp Queue.cpp Serial.cpp \
             CriticalSection.cpp Mutex.cpp Semaphore.cpp Scheduler.cpp Task.cpp
