import os

Import('env')

localEnv = env.Clone()

target = 'freertos-cc2538'
source = ['main.cpp']

main = localEnv.Program(
    target = target,
    source = source,
    LIBS = env['lib_name'],
    LIBPATH = env['lib_path']
)

Return('main')
