import os

Import('env')

localEnv = env.Clone()

source = [
    'At86rf215.cpp',
    'At86rf215_conf.cpp'
]

localEnv.Append(
    CPPPATH=[]
)

common = localEnv.Object(source=source)

Return('common')
