import os

Import('env')

localEnv = env.Clone()

project   = 'freertos-tickless'
extension = '.elf'

target = project + extension
source = [
    'main.cpp',
    'cc2538_lowpower.c'
]

main = localEnv.Program(
    target = target,
    source = source,
    LIBS = env['lib_name'],
    LIBPATH = env['lib_path']
)

Return('main')
