import os

Import('env')

localEnv = env.Clone()

project   = 'ieee802154-sniffer'
extension = '.elf'

target = project + extension
source = [
	'main.cpp',
	'SnifferCommon.cpp',
	'SnifferSerial.cpp'
]

output = localEnv.Program(
    target = target,
    source = source,
    LIBS = env['lib_name'],
    LIBPATH = env['lib_path']
)

Return('output')
