# Project name and files to compile
PROJECT_NAME  = freertos
PROJECT_FILES = freertos.cpp

# Location of the root directory
PROJECT_HOME = ../..

# Configure compiling
USE_KERNEL = TRUE
USE_LIBRARY = TRUE

# Append to the include path
INC_PATH += -I .

# Include the Makefile in the root directory
include $(PROJECT_HOME)/Makefile.include
