# Project name and files to compile
PROJECT_NAME  = hello-world
PROJECT_FILES = hello-world.c

# Location of the root directory
PROJECT_HOME = ../..

# Configure compiling
USE_KERNEL = FALSE

# Include the Makefile in the root directory
include $(PROJECT_HOME)/Makefile.include
