import os

Import('env')

localEnv = env.Clone()

target = 'test-task.elf'
source = ['main.cpp', 'LedBlinker.cpp']

output = localEnv.Program(
    target  = target,
    source  = source,
    LIBS    = localEnv['lib_name'],
    LIBPATH = localEnv['lib_path']
)

Return('output')
