# Project name and files to compile
PROJECT_NAME  = freertos-tickless
PROJECT_FILES = freertos-tickless.cpp tickless.c
PROJECT_DIR   = .

# Location of the root directory
PROJECT_HOME = ../..

INC_PATH += -I $(PROJECT_DIR)

# Configure compiling
USE_KERNEL = TRUE
USE_LIBRARY = TRUE

# Include the Makefile in the root directory
include $(PROJECT_HOME)/Makefile.include
