# 
CONNECTIVITY_ENC28J60  = $(CONNECTIVITY_PATH)/enc28j60

# Append to the include path
SRC_PATH += -I $(CONNECTIVITY_ENC28J60)
INC_PATH += -I $(CONNECTIVITY_ENC28J60)

# Extend the virtual path
VPATH += $(CONNECTIVITY_ENC28J60)

# Include the Makefiles in the various subdirectories in the current folder
include $(CONNECTIVITY_ENC28J60)/Makefile.include

