import os

Import('env')

localEnv = env.Clone()

target = 'earthquake'
source = ['main.cpp']

earthquake = localEnv.Program(
    target = target,
    source = source,
    LIBS = env['lib_name'],
    LIBPATH = env['lib_path']
)

Return('earthquake')
