# Project name and files to compile
PROJECT_NAME  = freertos-sensors
PROJECT_FILES = freertos-sensors.cpp
PROJECT_DIR   = .

# Location of the root directory
PROJECT_HOME = ../..

# Include the current path
INC_PATH += -I $(PROJECT_DIR)

# Define options passed to the C compiler
DOPTIONS +=

# Configure compiling
USE_KERNEL = TRUE
USE_LIBRARY = TRUE

# Include the Makefile in the root directory
include $(PROJECT_HOME)/Makefile.include
