import os

Import('env')

localEnv = env.Clone()

target = 'demo-tx'
source = ['main.cpp', 'cc2538_lowpower.c']

main = localEnv.Program(
    target = target,
    source = source,
    LIBS = env['lib_name'] + ['m'],
    LIBPATH = env['lib_path']
)

Return('main')
