# Project name and files to compile
PROJECT_NAME  = tickless
PROJECT_FILES = tickless.cpp
PROJECT_DIR   = .

# Location of the root directory
PROJECT_HOME = ../..

INC_PATH += -I $(PROJECT_DIR)

# Configure compiling
USE_KERNEL = FALSE
USE_LIBRARY = TRUE

# Include the Makefile in the root directory
include $(PROJECT_HOME)/Makefile.include
