import os

Import('env')

localEnv = env.Clone()

target = 'libnet'

src_dir   = ['sniffer']
output_dir = os.path.join('#', 'bin', env['board'])
source = []

for src in src_dir:
    script = os.path.join('#', 'net', src, 'SConscript')
    build  = os.path.join('#', 'build', localEnv['board'], 'net', src)
    output = localEnv.SConscript(
        script,
        variant_dir = build,
        duplicate = 0,
        exports = {'env': env},
    )
    source.append(output)

libnet = localEnv.StaticLibrary(
    target = target,
    source = source,
)

result = env.Install(output_dir, libnet)
