import os

Import('env')

localEnv = env.Clone()

target = 'freertos-tickless'
source = ['main.cpp', 'cc2538_lowpower.c']

main = localEnv.Program(
    target = target,
    source = source,
    LIBS = env['lib_name'],
    LIBPATH = env['lib_path']
)

Return('main')
